'use client'

import { useState, useMemo } from 'react'
import type { Track } from '../dashboard/page'

type Props = {
  tracks: Track[]
  timeRangeLabel: string
}

type Filter = 'all' | 'genre' | 'deep_cuts' | 'mainstream' | 'throwbacks' | 'recent'

const FILTER_META: Record<Filter, { label: string; description: string; icon: string }> = {
  all:         { label: 'All Tracks',      description: 'Your entire top tracks list',         icon: '♫' },
  genre:       { label: 'By Genre',        description: 'Pick specific genres to include',     icon: '◉' },
  deep_cuts:   { label: 'Deep Cuts',       description: 'Hidden gems (popularity < 40)',       icon: '♦' },
  mainstream:  { label: 'Mainstream Hits',  description: 'Popular bangers (popularity > 70)',   icon: '★' },
  throwbacks:  { label: 'Throwbacks',       description: 'Released before 2010',               icon: '⏪' },
  recent:      { label: 'Recent Finds',    description: 'Released in the last 2 years',        icon: '✦' },
}

export default function PlaylistCreator({ tracks, timeRangeLabel }: Props) {
  const [activeFilter, setActiveFilter] = useState<Filter>('all')
  const [selectedGenres, setSelectedGenres] = useState<Set<string>>(new Set())
  const [playlistName, setPlaylistName] = useState('')
  const [creating, setCreating] = useState(false)
  const [result, setResult] = useState<{ url: string; name: string } | null>(null)
  const [error, setError] = useState<string | null>(null)

  // Build genre list from tracks
  const allGenres = useMemo(() => {
    const counts: Record<string, number> = {}
    for (const track of tracks) {
      for (const g of track.genres) {
        counts[g] = (counts[g] ?? 0) + 1
      }
    }
    return Object.entries(counts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 20)
  }, [tracks])

  // Filter tracks based on active filter
  const filteredTracks = useMemo(() => {
    const now = new Date().getFullYear()
    switch (activeFilter) {
      case 'genre':
        if (selectedGenres.size === 0) return tracks
        return tracks.filter((t) => t.genres.some((g) => selectedGenres.has(g)))
      case 'deep_cuts':
        return tracks.filter((t) => t.popularity < 40)
      case 'mainstream':
        return tracks.filter((t) => t.popularity > 70)
      case 'throwbacks':
        return tracks.filter((t) => {
          const year = parseInt(t.release_date?.slice(0, 4) ?? '0')
          return year > 0 && year < 2010
        })
      case 'recent':
        return tracks.filter((t) => {
          const year = parseInt(t.release_date?.slice(0, 4) ?? '0')
          return year >= now - 2
        })
      default:
        return tracks
    }
  }, [tracks, activeFilter, selectedGenres])

  const toggleGenre = (genre: string) => {
    setSelectedGenres((prev) => {
      const next = new Set(prev)
      if (next.has(genre)) next.delete(genre)
      else next.add(genre)
      return next
    })
  }

  const defaultName = `Music DNA — ${FILTER_META[activeFilter].label}`

  const handleCreate = async () => {
    if (filteredTracks.length === 0) return
    setCreating(true)
    setError(null)
    setResult(null)

    try {
      const res = await fetch('/api/create-playlist', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: playlistName.trim() || defaultName,
          description: `Generated by Music Taste DNA — ${FILTER_META[activeFilter].label} (${timeRangeLabel})`,
          track_ids: filteredTracks.map((t) => t.id),
        }),
      })

      if (!res.ok) {
        setError('Failed to create playlist. Try again.')
        return
      }

      const data = await res.json()
      setResult({ url: data.playlist_url, name: data.name })
    } catch {
      setError('Something went wrong. Check your connection.')
    } finally {
      setCreating(false)
    }
  }

  return (
    <div className="space-y-6">
      {/* Filter cards */}
      <div className="grid grid-cols-2 sm:grid-cols-3 xl:grid-cols-6 gap-3">
        {(Object.keys(FILTER_META) as Filter[]).map((f) => (
          <button
            key={f}
            onClick={() => { setActiveFilter(f); setResult(null); setError(null) }}
            className={`text-left p-4 rounded-2xl border transition-all ${
              activeFilter === f
                ? 'bg-pink-500/15 border-pink-500/40 text-white'
                : 'bg-gray-900 border-gray-800 text-gray-400 hover:border-gray-700 hover:text-gray-300'
            }`}
          >
            <span className="text-xl block mb-2">{FILTER_META[f].icon}</span>
            <p className="text-sm font-medium">{FILTER_META[f].label}</p>
            <p className="text-xs text-gray-500 mt-0.5">{FILTER_META[f].description}</p>
          </button>
        ))}
      </div>

      {/* Genre picker (only when genre filter active) */}
      {activeFilter === 'genre' && (
        <div className="bg-gray-900 rounded-2xl p-5">
          <p className="text-sm font-medium mb-3">Select genres to include</p>
          <div className="flex flex-wrap gap-2">
            {allGenres.map(([genre, count]) => (
              <button
                key={genre}
                onClick={() => toggleGenre(genre)}
                className={`text-xs px-3 py-1.5 rounded-full border transition-colors capitalize ${
                  selectedGenres.has(genre)
                    ? 'bg-pink-500 border-pink-500 text-white'
                    : 'border-gray-700 text-gray-400 hover:border-gray-500'
                }`}
              >
                {genre} <span className="text-gray-500 ml-1">({count})</span>
              </button>
            ))}
          </div>
          {allGenres.length === 0 && (
            <p className="text-gray-500 text-sm">No genre data available for your tracks.</p>
          )}
        </div>
      )}

      {/* Preview */}
      <div className="bg-gray-900 rounded-2xl p-5">
        <div className="flex items-center justify-between mb-4">
          <div>
            <p className="text-sm font-medium">
              {filteredTracks.length} track{filteredTracks.length !== 1 ? 's' : ''} selected
            </p>
            <p className="text-xs text-gray-500">{FILTER_META[activeFilter].description}</p>
          </div>
        </div>

        {/* Track preview list */}
        <div className="max-h-64 overflow-y-auto space-y-1 mb-5 scrollbar-thin">
          {filteredTracks.length > 0 ? (
            filteredTracks.map((track, i) => (
              <div key={track.id} className="flex items-center gap-3 py-1.5 px-2 rounded-lg hover:bg-gray-800/50">
                <span className="text-gray-600 text-xs w-5 text-right font-mono shrink-0">{i + 1}</span>
                {track.image && (
                  <img src={track.image} alt="" className="w-8 h-8 rounded shrink-0" />
                )}
                <div className="min-w-0 flex-1">
                  <p className="text-sm truncate">{track.name}</p>
                  <p className="text-xs text-gray-500 truncate">{track.artists.join(', ')}</p>
                </div>
                <span className="text-xs text-gray-600 shrink-0">{track.popularity}</span>
              </div>
            ))
          ) : (
            <p className="text-gray-500 text-sm text-center py-6">
              No tracks match this filter. Try a different one.
            </p>
          )}
        </div>

        {/* Name + Create */}
        {filteredTracks.length > 0 && (
          <div className="flex flex-col sm:flex-row gap-3 pt-4 border-t border-gray-800">
            <input
              type="text"
              value={playlistName}
              onChange={(e) => setPlaylistName(e.target.value)}
              placeholder={defaultName}
              className="flex-1 bg-gray-800 border border-gray-700 rounded-xl px-4 py-2.5 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-pink-500 transition-colors"
            />
            <button
              onClick={handleCreate}
              disabled={creating}
              className="bg-pink-500 hover:bg-pink-400 disabled:bg-pink-500/50 text-white text-sm font-semibold px-6 py-2.5 rounded-xl transition-colors shrink-0"
            >
              {creating ? 'Creating...' : 'Create Playlist'}
            </button>
          </div>
        )}

        {/* Result */}
        {result && (
          <div className="mt-4 bg-green-950/30 border border-green-800/40 rounded-xl p-4 flex items-center gap-3">
            <span className="text-green-400 text-lg">✓</span>
            <div className="flex-1">
              <p className="text-sm font-medium text-green-300">Playlist created!</p>
              <p className="text-xs text-gray-400">&quot;{result.name}&quot; — {filteredTracks.length} tracks</p>
            </div>
            <a
              href={result.url}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs font-medium text-green-400 hover:text-green-300 border border-green-700 px-3 py-1.5 rounded-lg transition-colors"
            >
              Open in Spotify
            </a>
          </div>
        )}

        {error && (
          <div className="mt-4 bg-red-950/30 border border-red-800/40 rounded-xl p-4">
            <p className="text-sm text-red-400">{error}</p>
          </div>
        )}
      </div>
    </div>
  )
}
